# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
  'master' => {'memory' => '2048', 'cpus' => 2, 'ip' => '10', 'provision' => 'master.sh'},
  'minion1' => {'memory' => '1024', 'cpus' => 1, 'ip' => '20', 'provision' => 'minion.sh'}
  # 'minion2' => {'memory' => '1024', 'cpus' => 1, 'ip' => '30', 'provision' => 'minion.sh'}
}

Vagrant.configure('2') do |config|

  config.vm.box = 'debian/buster64'
  config.vm.box_check_update = false

  config.vm.provision "file", source: "../kubernetes", destination: "/home/vagrant/"
  config.vm.provision 'shell', path: 'provision/provision.sh'

  vms.each do |name, conf|
    config.vm.define "#{name}" do |k|
      k.vm.hostname = "#{name}.k8s.com"
      k.vm.network 'private_network', ip: "172.100.100.#{conf['ip']}"
      k.vm.provider 'virtualbox' do |vb|
        vb.memory = conf['memory']
        vb.cpus = conf['cpus']
      end
      # provisining in kvm
      # k.vm.provider 'libvirt' do |lv|
      #   lv.memory = conf['memory']
      #   lv.cpus = conf['cpus']
      #   lv.cputopology :sockets => 1, :cores => conf['cpus'], :threads => '1'
      # end
      k.vm.provision 'shell', path: "provision/#{conf['provision']}", args: "#{conf['ip']}"
    end
  end

end
